/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jfondo.version1;

//import javax.swing.Icon;
import java.awt.Color;
import java.awt.Component;
import javax.swing.ImageIcon;

/**
 *
 * @author Sergio Teacher
 */
public class VentanaFondo extends javax.swing.JFrame {

ImageIcon miIcono;
    /**
     * Creates new form VentanaFondo
     */
    public VentanaFondo() {
        initComponents();
        System.out.println("Iniciando Ventana Fondo");
        setBounds(0,0,300,250);
        this.setLocationRelativeTo(null);

// Carga un objeto ImageIcon
miIcono = new ImageIcon( new ImageIcon(getClass().getResource("/jfondo/imagenes/sheep.png")).getImage().getScaledInstance(txtFoto.getWidth(), txtFoto.getHeight(), 0) );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelNorte = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanelSur = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanelEste = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtFoto = new javax.swing.JLabel();
        btnIncrustar = new javax.swing.JButton();
        jPanelOeste = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnCargar = new javax.swing.JButton();
        jPanelCentral = new javax.swing.JPanel();
        jPanelFondo = new javax.swing.JPanel();
        btnborra = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Fondo version 1");

        jPanelNorte.setBackground(new java.awt.Color(204, 255, 204));
        jPanelNorte.add(jLabel4);

        getContentPane().add(jPanelNorte, java.awt.BorderLayout.PAGE_START);

        jPanelSur.setBackground(new java.awt.Color(204, 255, 204));
        jPanelSur.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel3.setText("Con el JPanel decorado sí puedes añadir objetos");
        jPanelSur.add(jLabel3);

        getContentPane().add(jPanelSur, java.awt.BorderLayout.PAGE_END);

        jPanelEste.setBackground(new java.awt.Color(204, 255, 204));
        jPanelEste.setMinimumSize(new java.awt.Dimension(200, 200));
        jPanelEste.setLayout(new javax.swing.BoxLayout(jPanelEste, javax.swing.BoxLayout.Y_AXIS));

        jLabel2.setBackground(new java.awt.Color(204, 255, 204));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("JLabel");
        jPanelEste.add(jLabel2);

        txtFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jfondo/imagenes/miniCat.png"))); // NOI18N
        jPanelEste.add(txtFoto);

        btnIncrustar.setBackground(new java.awt.Color(255, 255, 255));
        btnIncrustar.setText("Incrustar");
        btnIncrustar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncrustarActionPerformed(evt);
            }
        });
        jPanelEste.add(btnIncrustar);

        getContentPane().add(jPanelEste, java.awt.BorderLayout.LINE_END);

        jPanelOeste.setBackground(new java.awt.Color(204, 255, 204));
        jPanelOeste.setLayout(new javax.swing.BoxLayout(jPanelOeste, javax.swing.BoxLayout.Y_AXIS));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("JPanel");
        jPanelOeste.add(jLabel1);

        btnCargar.setBackground(new java.awt.Color(255, 255, 255));
        btnCargar.setText("Cargar");
        btnCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarActionPerformed(evt);
            }
        });
        jPanelOeste.add(btnCargar);

        getContentPane().add(jPanelOeste, java.awt.BorderLayout.LINE_START);

        jPanelCentral.setBackground(new java.awt.Color(204, 255, 204));
        jPanelCentral.setLayout(new java.awt.BorderLayout());

        btnborra.setText("x");
        btnborra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnborraActionPerformed(evt);
            }
        });
        jPanelFondo.add(btnborra);

        jPanelCentral.add(jPanelFondo, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanelCentral, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIncrustarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncrustarActionPerformed
        txtFoto.setIcon(miIcono);
    }//GEN-LAST:event_btnIncrustarActionPerformed

    private void btnCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarActionPerformed
        JPanelImage mImagen = new JPanelImage(jPanelFondo, "/jfondo/imagenes/sheep.png");
        jPanelFondo.add(mImagen).repaint();

        //no se vea el panel
        jPanelFondo.setOpaque(false);
        jPanelFondo.setBorder(null);
        //Color transparente
        jPanelFondo.setBackground(new Color(0,0,0,0));
    }//GEN-LAST:event_btnCargarActionPerformed

/**
* Recorre los componentes y borra los de tipo JPanelImage
* @param evt el evento que lo lanza
*/
    private void btnborraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnborraActionPerformed
        for( Component c: jPanelFondo.getComponents() ){
            if( c instanceof JPanelImage ){
                jPanelFondo.remove(c);
            }
        }

        jPanelFondo.revalidate();
        jPanelFondo.repaint();
    }//GEN-LAST:event_btnborraActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCargar;
    private javax.swing.JButton btnIncrustar;
    private javax.swing.JButton btnborra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanelCentral;
    private javax.swing.JPanel jPanelEste;
    private javax.swing.JPanel jPanelFondo;
    private javax.swing.JPanel jPanelNorte;
    private javax.swing.JPanel jPanelOeste;
    private javax.swing.JPanel jPanelSur;
    private javax.swing.JLabel txtFoto;
    // End of variables declaration//GEN-END:variables
}
